### ISSUE TITLE
Autocompletion of filterby options not working

### ISSUE THREAD

**Issue by grayfold3d** [swimlane/PSAttck#5]
I watched the usage videos at : https://swimlane.com/analyst-hub/ and it looks like I should be able to use the autocomplete on the `filterby` parameter to do something like this:

`Get-Attck -actor -filterby`

When doing so, I get the following: 

```
 Get-Attck -Actor -FilterBy                                                                                                                                                                       Get-Attck : Missing an argument for parameter 'FilterBy'. Specify a parameter of type 'System.Object' and try again.
At line:1 char:18
+ Get-Attck -Actor -FilterBy
+                  ~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Get-Attck], ParameterBindingException
    + FullyQualifiedErrorId : MissingArgument,Get-Attck
```

**Comment by MSAdministrator** [comment]
@grayfold3d sorry for the delay - You can use `-FilterBy` but you must provide a value.  I just released a new version anyways so please update to that version and try again.

Thanks!
